<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net20;net451;netstandard2.0;net6.0;net8.0</TargetFrameworks>
		<LangVersion>10.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\MemoryModule\MemoryModule.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="libflzma2_x64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="libflzma2_x86.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
