<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net20;net451;netstandard2.0;net6.0;net8.0</TargetFrameworks>
		<LangVersion>10.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>CS1591</NoWarn>
		<IsAotCompatible Condition="'$(TargetFramework)'=='net8.0'">true</IsAotCompatible>
	</PropertyGroup>
	<PropertyGroup>
		<Description>Library to load a DLL from memory.</Description>
		<Copyright>Copyright © 2018-2024 Wwh</Copyright>
		<Version>1.0.0.3</Version>
	</PropertyGroup>
</Project>
